### ISSUE TITLE
Pretrained Models

### ISSUE THREAD

**Issue by ldkong1205** [SenZHANG-GitHub/ekf-imu-depth#2]
Hi @chaimi2013 @SenZHANG-GitHub, thank you for open-sourcing your work!

Would you like to release your pretrained weights for reproduction? Thanks!

**Comment by SenZHANG-GitHub** [comment]
> Hi @chaimi2013 @SenZHANG-GitHub, thank you for open-sourcing your work!
> 
> Would you like to release your pretrained weights for reproduction? Thanks!

Sure. We will release the weights shortly in this month.

**Comment by ldkong1205** [comment]
Thanks a lot and looking forward to it!

**Comment by SenZHANG-GitHub** [comment]
> Hi @chaimi2013 @SenZHANG-GitHub, thank you for open-sourcing your work!
> 
> Would you like to release your pretrained weights for reproduction? Thanks!

Hi @ldkong1205 , thanks for your reminder and sorry for the delay! I have updated README.md to include detailed data preprocessing steps and the links to the pretrained models (DynaDepth R18 and R50 that use the ResNet18 and ResNet50 as the backbone, respectively).

**Comment by SenZHANG-GitHub** [comment]
> Hi @chaimi2013 @SenZHANG-GitHub, thank you for open-sourcing your work!
> 
> Would you like to release your pretrained weights for reproduction? Thanks!

As for the preprocessing part, since the unsync kitti dataset is quite large. We also have updated the link to our preprocessed imu files in README.md. Feel free to check them : )
