### ISSUE TITLE
About matched_oxts.txt

### ISSUE THREAD

**Issue by JunjieLiuSWU** [SenZHANG-GitHub/ekf-imu-depth#3]
Hello. Could you provide the files after executing match_kitti_imu.py?

**Comment by SenZHANG-GitHub** [comment]
> Hello. Could you provide the files after executing match_kitti_imu.py?

Hi @JunjieLiuSWU  , thanks for your interest in our work. We have updated the detailed preprocessing description and I guess now it should be easy for you to run match_kitti_imu.py to get the matched_oxt/ for the sequences in your setting

**Comment by SenZHANG-GitHub** [comment]
> Hello. Could you provide the files after executing match_kitti_imu.py?

Also, I'm uploading the matched imu files into the netdisk. It's a bit slow and should be ready tonight or tomorrow.

**Comment by SenZHANG-GitHub** [comment]
> Hello. Could you provide the files after executing match_kitti_imu.py?

I realized that downloading the entire unsync dataset can be troublesome since it is quite large, as reminded in other issues. Thus I have also updated the link to our preprocessed imu files in README.md. Feel free to check them : ) As for image preprocessing, please be aware that we follow the practice in monodepth2 to convert the image format from png to jpg to accelerate the training process.

**Comment by imbinwang** [comment]
Thank you for sharing the work @SenZHANG-GitHub . Could you please give another link of matched_imus?

**Comment by SenZHANG-GitHub** [comment]
> 

Hi @imbinwang I have updated the link in README.md, specially,

_Since the unsync dataset is quite large to download, we also provide our preprocessed imu files in the following link: https://pan.baidu.com/s/1971KrQEHw5kVRy_Y4Lj5FA pwd:80pz_

I have tried this link just now and it seems to work for me. Is there any problem for you to access this file? I actually don't have enough space in my google drive or dropbox account for it. If Baidu Netdisk does not work for you, could you recommend an alternative netdisk with free space to upload this file?

**Comment by imbinwang** [comment]
> > 
> 
> Hi @imbinwang I have updated the link in README.md, specially,
> 
> _Since the unsync dataset is quite large to download, we also provide our preprocessed imu files in the following link: https://pan.baidu.com/s/1971KrQEHw5kVRy_Y4Lj5FA pwd:80pz_
> 
> I have tried this link just now and it seems to work for me. Is there any problem for you to access this file? I actually don't have enough space in my google drive or dropbox account for it. If Baidu Netdisk does not work for you, could you recommend an alternative netdisk with free space to upload this file?

Thanks for your fast reply. I have downloaded the data by installing Baidu Netdisk app at last.
