### ISSUE TITLE
How to train on custom data

### ISSUE THREAD

**Issue by mengpengfei** [SenZHANG-GitHub/ekf-imu-depth#5]
I have RTK data and image data，and I have matched RTK data to the image data。Can I train the network on my custom data。
Wait for your help.

**Comment by SenZHANG-GitHub** [comment]
> I have RTK data and image data，and I have matched RTK data to the image data。Can I train the network on my custom data。 Wait for your help.

Yes I think the easiest way is to formulate your data in the same way as KITTI to use our codebase. There are two concerns regarding the IMU data: (1) Make sure the axes of your RTK data are correctly aligned, (2) The images and imu data are sampeld at 10 Hz and 100 Hz in KITTI. If your data is different, you may need to modify some codes to fit your setting, e.g. line 390-413 in datasets/mono_dataset.py
